### ISSUE TITLE
Is it windows only?

### ISSUE THREAD

**Issue by gregbenner** [TommyR22/System-Utility-Monitor#4]
Doesn't seem to show data on Ubuntu 20.04
![Screenshot from 2020-08-11 01-13-56](https://user-images.githubusercontent.com/1177690/89859904-1302eb80-db70-11ea-8e7a-e350cc08988a.png)

**Comment by TommyR22** [comment]
I've used this nodejs library to get OS params: https://www.npmjs.com/package/node-os-utils
but you can use another one.
I've tried only with windows, maybe linux/mac are not supported.
You should debug this file: https://github.com/TommyR22/System-Utility-Monitor/blob/master/src/helpers/systemDetails.ts
